### PR TITLE
Added flags to control output structure & another flag for flat dumps

### PR DESCRIPTION
**Pull request by CollinShoop**
Hey @WoozyMasta 👋🏻 Very cool project, I was looking at making something just like this and figured I should contribute instead. 

For my own use, having better control over the output structure would be ideal. I personally do not require resources to be broken up per file, and I also sometimes need all the detailed fields which were being removed via `jq` for debugging purposes (as opposed to backups, which I presume is the primary use case for this tool), so I've added a few new flags.

### CODE REVIEW

**Comment by WoozyMasta** [comment]
Hey
Looks cool, I've been wanting to make the `--output-by-type` mode for a long time, special thanks for that.

I'll have to find some time to check it all out. And I think these edits will be included in the new version.

**Comment by WoozyMasta** [comment]
Do you have time to update the "Commands and Flags" section in the [`README.md`](https://github.com/WoozyMasta/kube-dump#commands-and-flags) and the [`.env`](https://github.com/WoozyMasta/kube-dump/blob/master/.env) file with the new options? It would be great.

**Comment by WoozyMasta** [comment]
@CollinShoop, I researched the solution a little.

Shouldn't the `--output-by-type` and `--flat` keys be checked for the presence of a resource. When saving all available namespace resources (a couple of deployments), a large number of empty directories or files are created, especially if there are a large number of CRDs in the cluster.

Do you think it will not be difficult to implement it, and is it worth it?

After all, when I specify specific resources, only they are saved.

For example:
```bash
./kube-dump ns -n dev-app -r deployment,svc --output-by-type 
```

**Review by WoozyMasta — APPROVED** [review]

**Comment by WoozyMasta** [comment]
In any case, I accepted the changes and released the new version 1.1.0.

Thank you so much for the work done.

**Comment by CollinShoop** [comment]
Thanks for the quick review & merge 🥇 

> @CollinShoop, I researched the solution a little.
> 
> Shouldn't the `--output-by-type` and `--flat` keys be checked for the presence of a resource. When saving all available namespace resources (a couple of deployments), a large number of empty directories or files are created, especially if there are a large number of CRDs in the cluster.
> 
> Do you think it will not be difficult to implement it, and is it worth it?
> 
> After all, when I specify specific resources, only they are saved.
> 
> For example:
> 
> ```shell
> ./kube-dump ns -n dev-app -r deployment,svc --output-by-type 
> ```

I had the same observation when testing this, but my reasoning for keeping as-is is that it may be better to positively indicate that there are none of a particular resource with an empty file than to omit it which could be ambiguous (ie did the dump even check that resource type?). It's a bit annoying in the case of empty namespaces, though, but I'm not sure of a simple way to avoid that now. 

> Do you have time to update the "Commands and Flags" section in the [README.md](https://github.com/WoozyMasta/kube-dump#commands-and-flags) and the [.env](https://github.com/WoozyMasta/kube-dump/blob/master/.env) file with the new options? It would be great.

I'll add this to my TODO 👍🏻

**Comment by CollinShoop** [comment]
Actually, I see you've already updated the README.md and .env 💯

**Pull request merged**
